### ISSUE TITLE
[Enhancement] Allow to set private or hidden pictures in public albums

### ISSUE THREAD

**Issue by bastantoine** [LycheeOrg/Lychee#1039]
Hello,

I noticed recently that when you set an album public, you cannot fine-tune the privacy settings to a picture level. So when you access the visibility settings popup for a picture in a public album, you see a message: *"Because this photo is located in a public album, it inherits that album's visibility settings. Its current visibility is shown below for informational purposes only."* and you cannot change anything there.

![Capture d’écran 2021-06-20 à 22 17 45](https://user-images.githubusercontent.com/8548006/122687672-ebf95980-d217-11eb-8eba-fd651cbe0701.png)

I believe it would be useful to be able to override the album visibility settings for a specific set of pictures.

Here's how I see it:
- If you're not connected: you see only the public pictures.
- If you're connected: you see all the public pictures, plus the hidden ones and those private you have the rights to see.

When you change the visibility settings of an album, this cascades down to all its direct child pictures, but not the child albums.

What do you think? I can work on a PR if you think it's a good idea.

**Comment by nagmat84** [comment]
I agree that this would be plus.

Give the current state of the backend it would be difficult to implement it as the state of visibility of a photo is independently determined at various places (i.e. there is a lot of code duplication). However, I am cleaning up a lot at the backend and after I have finished that, the backend logic to realize that would be fairly simple to implement.

But we also must consider the frontend which is somewhat at end-of-life. For myself, I would not like to make the effort to incorporate those enhancements in the current (end-of-life) frontend. Moreover, I am not a talented frontend programmer. I know that @ildyria is working on the new version of the frontend. Maybe this would be an option for the new frontend in the future.

**Comment by ildyria** [comment]
I don't mind adding this as an option in the new front-end but I first need to incorporate 90% of the current front-end for it even usable. :)

**Comment by nagmat84** [comment]
I know. My post wasn't meant to put more workload onto you, but to inform the original poster that the idea is great but may have to wait some time. Personally, I would like to postpone any enhancement which is more than absolutely trivial until the new frontend is out and only fix security issues of the current frontend until then.

**Comment by kamil4** [comment]
Yeah, we do get requests every so often to overhaul the permissions/visibility settings in Lychee. So clearly there is a desire from the user community for a more capable system. On the other hand, I remember a conversation between us developers in the past on whether we should get rid off picture-level settings entirely and only keep the album-level (we left things as-is, but mostly because it was already there, not because we liked it).

This proposal is fairly modest in scope so I suppose it stands a better chance than most. Even so, it's not just a matter of enabling a few buttons in the front end. The photos table will need additional columns to support this (I believe only the visibility is currently a column there?).

@nagmat84 I agree that we shouldn't implement entire new features in the current front end. But I expect it will be a while before the new front end is production-ready, so I think we should keep pushing regular bug fixes and minor enhancements.

**Comment by sunosv** [comment]
@ildyria  May I ask when the Lychee version will be updated. It's been too long that I have not seen the new version.

**Comment by Gaibhne** [comment]
I would like to contribute that I would also like a feature like this, because in my family, we have agreed not to publicly share pictures of the kids, so often we have a family vacation album where we want to mark a handful of pictures to be private so we can still easily share the vacation pics, but still allow for the private pictures to be in there, visible to family members who are logged in.

**Comment by ildyria** [comment]
Photo can no longer be made public individually.
