### ISSUE TITLE
Scrolling general not work in my Installation

### ISSUE THREAD

**Issue by susoftch** [LycheeOrg/Lychee#1042]
Scrolling in the Gallery, setting or in album is not possible in my installation.

### Steps to reproduce the issue
this are viewable in one of my albums -> https://alpegruess.ch/Lychee/public/#16237656530148

**Screenshots**
Screenshot from the gallery, without scrollbar on the left site:
![Gallery without scrollbar](https://user-images.githubusercontent.com/7894914/123506052-7e5b8c00-d662-11eb-85dc-b69b158ca21d.jpg)
Screenshot from a album, without scrollbar on the left site:
![album without scrollbar](https://user-images.githubusercontent.com/7894914/123506067-9af7c400-d662-11eb-9f1d-56516d8e9d1a.jpg)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
```

System Information
    --------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          100M
    Max post size:                   100M
    MySQL Version:                   10.5.11-MariaDB-1:10.5.11+maria~bionic
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1687
    GD Version:                      bundled (2.1.0 compatible)
```

### Browser and system
Chrome, Firefox, Edge and Safari on MacOS

**Comment by ildyria** [comment]
Well, I don't want to be mean, but you did it yourself. :|

See here: https://alpegruess.ch/Lychee/public/dist/user.css

```css
body {
  font-family: "Roboto", sans-serif;
  background: #ffffff;
  overflow: hidden; }
```

The `overflow: hidden` is basically telling your browser please ignore the length of the page and don't display the scrolling bar.

PS: I would seriously advise you to find a way to not give access to this folder: https://alpegruess.ch/Lychee/public

Ideally you would like to have your Lychee install directly, meaning: https://alpegruess.ch/Lychee/#16237656530148
instead of 
https://alpegruess.ch/Lychee/public/#16237656530148

See solutions for Nginx and Apache here: https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-nginx-like-httpsexampledevlychee

**Comment by susoftch** [comment]
Many thanks, for your fast response, this parameter was set with the provided installation

But now this works.

**Comment by d7415** [comment]
> this parameter was set with the provided installation

In that case you should report this to your provider.
