### ISSUE TITLE
[Enhancement] Enforce PHP 8 ?

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#1072]
As I see it there are multiple reasons to push this forward.

1. PHP 8 provides improvements in term of type checking (such as union types)
2. PHP 8 provides improvements in term of speed (JIT compilation).
3. Our dependencies are already pushing towards PHP 8, e.g. Laravel-feed (thank you spatie...)
4. We will depreciate PHP 7.4 on November 28th, 2021; so in 3 months. 

More about PHP 8 : https://stitcher.io/blog/new-in-php-8

**Comment by christianhorn** [comment]
I run Lychee with Debian stable, like probably many others too. Would be nice if php7 could stay supported while php8 is not in Debian stable.

**Comment by kamil4** [comment]
My understanding is that we drop support for old PHP versions once the PHP project itself drops those versions. See: https://www.php.net/supported-versions.php

**Comment by d7415** [comment]
Yeah. It's not great for stable distros like Debian that run older versions (with backported patches for security or major bugs), but we don't have resource to run multiple branches like that. If there was a security issue we might look into backporting a fix if there's demand, but otherwise older Lychee versions are available to download from [releases](https://github.com/LycheeOrg/Lychee/releases), check out as [tags](https://github.com/LycheeOrg/Lychee/tags) or pin as [docker images](https://github.com/LycheeOrg/Lychee-Docker#image-content) (though that's less relevant as they contain their own PHP).

We list any new PHP version requirements in the release notes.

**Comment by christianhorn** [comment]
Thanks for the hint, was not aware of https://www.php.net/supported-versions.php . That currently shows php7.4 security supported until 28 Nov 2022, that is a relief. Original post looks like just 2 month's of support left. 
I'm happy with Nov 2022. Because Lychee uses to many modules (which I consider as further surface and pieces which need to have an eye on), I run it in a Debian stable container. Even Fedora stable (34 currently) does not come with php8.

**Comment by d7415** [comment]
> Original post looks like just 2 month's of support left.

Yeah. For Lychee we generally use the "active support" window, rather than security.

**Comment by nagmat84** [comment]
@christianhorn I run Ubuntu 20.04 LTS (Focal) which also only provides PHP 7.4 out-of-the-box. **However there are good PPA for Debian as well as for Ubuntu which ship up-to-date versions of PHP.** This morning, I migrated to PHP 8 on my productive system and the migration process was straightforward. Also, the current version of Lychee and a Nextcloud installation on the same machine did not mind the upgrade to PHP 8.

The only PITA is that the PHP config for 7.4 resides in `/etc/php/7.4/{cli|fpm|apache2}/php.ini` and the config for 8.0 resides in `/etc/php/8.0/{cli|fpm|apache2}/php.ini`. As PHP 8.0 is a new major release the configuration has changed quite a bit. So it is not recommended to simply copy your old PHP config to the new place, but manually transfer your customized settings bit by bit (e.g. settings for max upload size, max timeout, max number of file per POST request, etc.)
