### ISSUE TITLE
Cannot import files with "0000:00:00 00:00:00" exif dates

### ISSUE THREAD

**Issue by dcarbone** [LycheeOrg/Lychee#1200]
### Detailed description of the problem [REQUIRED]
When a camera's battery dies, some set their internal clock to `0000:00:00 00:00:00`, and leave it there until it is manually set by it's operator.

In my exact example, there are three different exif fields this is present in:

* `CreateDate`
* `DateTimeOriginal`
* `ModifyDate`

Example extract using `exiftool`:

```
$ exiftool -T -CreateDate -DateTimeOriginal -ModifyDate DSCN2129.JPG 
0000:00:00 00:00:00	0000:00:00 00:00:00	0000:00:00 00:00:00
```

This particular camera is and older Nikon Coolpix, but I'm sure a similar issue impacts others.

What results is the following useless datetime value for the `taken_at` column: `-0001-11-30 00:00:00`, and MariaDB bombs when attempting to set this value.

I have had a quick look at the code in `Extractor::extract` starting at and following line `221`, and while it's too late for me to bother trying to be parse the logic and / or be clever, I may be able to do so tomorrow.

Perhaps even something as lazy as `if 0000:00:00 00:00:00 seen set to epoch` would suffice.

**Comment by nagmat84** [comment]
Thanks for the bug report! Nicely spotted.

I assume it should also break on PostgreSQL, because `0000-00-00 00:00:00` is simply no valid time and I wonder how `Carbon` (the PHP date/time class) behaves, especially when it comes to timezone conversion.

> Perhaps even something as lazy as if `0000:00:00 00:00:00` seen set to epoch would suffice.

In principle yes, but don't use epoch as a sentinal value. Epoch is a perfectly valid time. Instead, use `null`.

All these date attributes are optional and hence nullable. I believe it should be somewhere in the `MetaExtractor` (or similar): instead of returning the parsed datetime as a `Carbon` instance, return `null`. The string equality test should take place even before the string gets fed into the `Carbon` parsing function.

**Comment by nagmat84** [comment]
But as I said, we are always open to new contributors and PRs. The project is here https://github.com/LycheeOrg/php-exif. Feel free to code!
