### ISSUE TITLE
[Enhancement] Shorter shared album URLs

### ISSUE THREAD

**Issue by zkvvoob** [LycheeOrg/Lychee#1225]
Hello,

Could you perhaps see your way to simplifying the URL of a shared album? What I'd really like to be able to have is no `/gallery` slug, no `#`sign and the album ID to either be with fewer digits or, even better, a random alphanumeric string.

The reason for this is, when I share a link in a DM on Instagram, because of the `#`, the URL doesn't get converted into a link and some less tech-savvy recepients can't actually _click_ on it.

Thank you!

**Comment by nagmat84** [comment]
If you click on the "Share" button in the menu and select "As link", you will get a link for the currently visible photo/album which does not contain a hash tag. The URL will look like `https://your-domain.tld/r/<album-id>/<photo-id>`. The `r` in the URL stands for "redirection".

We actually have built this feature, because we are aware of the problem that Twitter and some other social media channels don't respect the HTTP standard, grab the hash tag for their own purposes and behave silly, if a hash tag occurs in a URL.

When you migrate to version 4.5.0 you will also see random alpha-numeric IDs. However, they are not shorter and cannot be made shorter without compromising security. Their length is selected to provide at least 128bit randomness in the IDs.

**Comment by zkvvoob** [comment]
I checked the Settings and after changing `share_button_visible=1`, I can still see no such button. There's "Share this album with users", but I don't have any other users, so I cannot replicate the behaviour @nagmat84 described above.

Could you help me figure out what I'm missing?

Currently running Lychee 4.4.0 in Docker.

Thanks!

**Comment by nagmat84** [comment]
As someone has asked somewhere, what I meant and where the button is. Here are the screenshots:

**For albums:**

![Screenshot_20220215_185235](https://user-images.githubusercontent.com/7428426/154122852-334e12b3-03cb-47ae-9b67-9eed226e0d1f.png)

**For photos:**

![Screenshot_20220215_185348](https://user-images.githubusercontent.com/7428426/154122894-06c074c6-c09f-409f-ae90-69bdd801b98c.png)

![Screenshot_20220215_185503](https://user-images.githubusercontent.com/7428426/154122908-ec999541-1512-457e-afe7-78af5f540aec.png)
