### ISSUE TITLE
Merge `Lychee` and `Lychee-front` repositories

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1286]
*This issue is a general idea/discussion and not a specific request. Feel free to just close it if you don't agree with me.*

Lychee currently uses a two-repo approach, a separated back- and frontend repository. According to [your website](https://lycheeorg.github.io/docs/node.html), the reason for this is to make it easier to use the same frontend for v3 and v4:

> At the moment, the current strategy of Lychee is to separate the front-end from the back-end. This allowed us to easily develop the version 4 while having the version 3 still live. It also kept the consistency of the GUI between the two major versions.

Separating it to have easier development is a good idea and fine for me, as long as you need it. But the [v3 repo](https://github.com/LycheeOrg/Lychee-v3) is archived, the last update is over two years ago, which means that there isn't really a reason to keep the repos separated (instead, do it the way it was done before too). My main reason for this is that this concept is pretty complex and hard(er) to understand for newcomers like me. It is much easier to have only one repository without submodules where you contribute your code to.

**Comment by nagmat84** [comment]
I understand that this split might be a hurdle for newcomers, but I would like to keep it. Even though the original reason has become obsolete as version 3 of the frontend is EOL, there are other frontends coming. For example, the native Android client I am working on. Hence, I would like to keep backend and frontend(s) separated.

However, there is some point I don't like about the split either. (But that happened before my time.) The split between backend and frontend is not consistent and the repositories are not really decoupled. Only the Javascript code (and the HTML code which is generated during runtime by Javascript) is part of the frontend repository. The initial and static HTML pages are still part of the backend. This is bad, because the Javascript code of the frontend repository needs to make assumptions about the HTML pages of the backend, otherwise the CSS selectors, which are used by the Javascript code, will fail. This introduces a strong coupling between the backend and the frontend which should not be there. IMHO, the only mutual dependencies should be the JSON API nothing else.

**Comment by qwerty287** [comment]
Yes, that's a way I would understand a split completely. There are applications which completely split back- and frontend (popular example is as far as I know [Mastodon](https://github.com/mastodon/mastodon), but they use a single repo), so you can run them on it's own and use e.g. different backend servers with one frontend server or different frontend servers with one backend server. Maybe a refactoring would be a good idea here to completely move this to such a model and remove all the endpoints that are not API-endpoints (i.e. UI endpoints) to static HTML/JS/CSS files. Using this way should completely remove frontend parts from the backend: submodule, compiled JS/CSS, images, localization files etc.

**Comment by ildyria** [comment]
Due to the nature of the new front end (available _Soon TM_) there will no longer be separation between Lychee and Lychee-front. The later will be retired. :)
