### ISSUE TITLE
Why  "Lychee is served out of the root of your web server, not a subdirectory"?

### ISSUE THREAD

**Issue by jlpoolen** [LycheeOrg/Lychee#1293]
The Installation documentation at https://lycheeorg.github.io/docs/installation.html#web-server-configuration states:

     It is strongly recommented _[sic]_ that Lychee is served out of the root of your web server, not a subdirectory.

I am pretty knowledgeable about Gentoo Linux systems and would like to install Lychee as a subdirectory. I actually would like to create a soft link to my staging area and give the link an unusual name.  I have several items on my web server and was concerned when I came across this recommendation.

Is the recommendation because some people may get tripped up, or are there hard-coded paths in the code?  It would be helpful to have a discussion on this so the reasoning is available to others who might have the same desire to _integrate_ Lychee into an existing server.

**Comment by nagmat84** [comment]
There are no hard-coded path in Lychee. If there were (but I am pretty sure there are exactly zero), this would be a bug. I used to serve Lychee out of a subdirectory (also on Gentoo) for quite a while. I changed that recently, but only due to other web apps which required a web root (e.g. Jitsi) and I wanted it to be consistent for all of my web apps.

I honestly don't know why it is phrased "strongly recommended". That has already been this way before I joined LycheeOrg as a developer. Maybe @ildyria knows more about it.

There are only at most two places which must be taken care of: In the `.env`-file, the variable `APP_URL` must be set correctly and potentially, the file `public/.htacess` may need some tweaking, if you are using Apache. Maybe, the rewrite rules need to be adopted, in particular the last rule `RewriteRule ^ index.php [L]` which replaces the entire URL (`^`) by `index.php`. However, if this needs to be adopted really depends on how your main Apache config looks like, in particular what Apache assumes to be your [rewrite base](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritebase). I did not need to change anything.

I believe our statement is only phrased this way to scare away middle-class administrators who try to create the craziest setup due to "security concerns" and some wild tips they found on Stack Overflow.

But there is one argument for using separate sub-domains: auto-completion. Lychee uses user-password authentication via a login form as most Web Applications do. The input fields are properly annotated as username and password. If you have several web applications served from the same domain, but from different sub-folders, browsers tend to be annoying when it comes to auto-completion, because browsers only use the domain name as the discriminating property. So if you use one pair of username and password for the one web application, another pair for Lychee and you save the password in the browser, browser will typically mix that up.

**Comment by jlpoolen** [comment]
@nagmat84 Thank you for the detailed response.  I shall, forthwith, attempt a subfolder installation and will update this issue with my findings in the next 5 days.

You point re: username/password caching getting confused is a good caveat to share with potential users.

**Comment by d7415** [comment]
https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-nginx-like-httpsexampledevlychee
https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee

**Comment by ildyria** [comment]
To clarify, it is possible to host lychee anywhere on your system.
On my dev machine I have it literally in my `~/Lychee` rather than `/var/www/html` or similar.
As long as you do proper configs (in my case apache) so that the directory are recognized in Apache, you give the proper access rights to the files and folders, it should work.

We do not recommend it because it make configuration slightly more tricky and will most likely have more people opening issue etc when they are the one F---ing up. :)

**Comment by jlpoolen** [comment]
I successfully installed Lychee as a subfolder attending to the various ownership/permissions issues.  No surprises, very straight-forward.  I think the documentation ought to be updated with wording that suggests alternatives can be pursued if you are an advanced user.  At least now, with this issue, we've documented a discussion and the links d7415 posted will be helpful.

Thank you, all.
