### ISSUE TITLE
Question : Hide elements; add html

### ISSUE THREAD

**Issue by larsnsonsk** [LycheeOrg/Lychee#1298]
Hi,
I have some general questions.
I want to hide some elements, e.g. the timestamp, creation date (on overlay and info). I thought I can just comment out the points from the html / php template but i didnt find some. I also want to add text in some places e.g. footer.
Can someone give me a hint how to do so ?

Another wish would be the landingpage, I would find it easier if you could click on the image or if the button to the gallery would be large in the middle. This would be easy to implement with html, but as I said I don't really seem to understand the whole concept ;)
I can deal with php/html and little js.

Thanks in advance for any hint!
And thanks for lychee!

**Comment by kamil4** [comment]
Thank you for your interest in Lychee!

As you may have noticed in the Settings, the overlay is configurable, including the ability to turn it off, although that only affects the defaults -- any person viewing your photos can cycle through the available options by clicking on the photo or using the "o" keyboard shortcut. If you so desire though, you should be able to hide the overlay completely using CSS: the selector to use is `div#image_overlay`.

That will still leave the info sidebar though. You couldn't find an HTML template because the code is generated dynamically by our JS frontend, specifically the function `sidebar.createStructure.photo` here: https://github.com/LycheeOrg/Lychee-front/blob/8507d67c2818b20bc722a229041948865d54812e/scripts/main/sidebar.js#L172. This is a source file BTW, that gets merged with other things into `Lychee/public/dist/main.js`. The correct way to modify it is to download the front end sources and compile them (the procedure is described in our manual, I believe). The hackish way is to instead edit `Lychee/public/dist/main.js` directly, but keep in mind that any changes you make this way will be lost on the next Lychee update. A less hackish approach would be again to customize it using CSS, although the result won't look perfect: you can hide the data on the right (e.g. use selector `span.attr_takedate` for `Captured` or `span.attr_uploaded` for `Uploaded`), but not the header on the left.

As to the footer, it's already pretty configurable -- if you go to the Settings and click on `More` at the bottom, you will find options such as `site_copyright_enable`, `additional_footer_text`, `display_social_in_gallery`, and `landing_owner`. These are documented at https://lycheeorg.github.io/docs/settings.html. If you want to tweak the footer further, the file to edit is `Lychee/resources/views/includes/footer.blade.php`.

I can't really help you much with the landing page as I don't use it myself. However, the file to edit is `Lychee/resources/views/landing.blade.php`.

Do not hesitate to ask should you need further help!

**Comment by larsnsonsk** [comment]
Thanks !
That already helps me a lot. I use CSS for some things for now, i could also modify the footer and so on. 
The Landingpage is not so important for now. I will try if i can modify the js but for now all works pretty fine for me :)

Thanks again !

**Comment by ildyria** [comment]
Seems this was answered.
