### ISSUE TITLE
Some album actions fail for tag albums

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1307]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
Trying to
* move
* merge

tag albums fails with 404. The actions in the context menu should be hidden.
```
2022-05-06 13:12:54 UTC -- error   -- Illuminate\Database\Eloquent\Builder::findOrFail -- 444 -- No query results for model [App\Models\Album] yOmWYwllfJsKkRsexgXeW8KI, Sq1hxi3pl3lsMogPrpEs3Fcr
``` 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Use the merge or move action on tag albums (context menu).

**Comment by nagmat84** [comment]
Even though this is probably a regression bug due to my big re-factoring, I am still proud of my new error handling mechanism. At least we now always know which specific line of code failed. 😎

**Comment by kamil4** [comment]
Yeah, this was already on my personal todo list as well...

Regarding error handling in general, I noticed that the front end does a dumb thing in some places of performing an operation (such as delete) by first updating the UI and only _then_ sending a request to the server. So if the request fails, the state of the UI becomes inconsistent with the DB. It's perplexing to me why it was coded that way in the first place since it's so easy to do it right by simply putting the UI update code in the success callback...

**Comment by nagmat84** [comment]
Totally agreed and I noticed that, too. However, this time I am very confident that _this_ is not a regression, but previous behaviour, because it struck me as insane, too, but I thought that this is intended due to some strange dependency I am unaware of.

**Comment by nagmat84** [comment]
> Trying to [...] fails with 500.

While it is clear why the actions fail and obviously the option to select those actions should be hidden in the first place, I wonder why they fail with a status code 500. Actually, it should have been an error in the range 4xx, because the client sent a bad request. In other words the error handler on the server does not work in the way it is meant to work.

@qwerty287 What setup do you use? Are you running Lychee in development or production environment? Is debugging enabled or not? Are the debugging dependencies installed or not? I would like to have a look into the error handler and why it does not fail the "right" way.

**Comment by qwerty287** [comment]
Sorry, my bad, it returns a 404 Not Found error. Seems that I misread the error message.

**Comment by nagmat84** [comment]
I tried several combinations (debug enabled, debug disabled but development dependencies install, debug disabled and no development dependencies installed) as well as merging/moving and I always get the expected 404 status report.

**Comment by nagmat84** [comment]
> Sorry, my bad, it returns a 404 Not Found error. Seems that I misread the error message.

Ah, the joys of concurrency and race conditions. I posted my comment the same moment as you.

**Comment by nagmat84** [comment]
A nice 404 error

![Screenshot_20220508_120656](https://user-images.githubusercontent.com/7428426/167291826-07ba03a0-fa6f-44fa-bbe5-9744d22824e9.png)

A full JSON response in debug mode (full name of exception class, incl. backtrace):

![Screenshot_20220508_120534](https://user-images.githubusercontent.com/7428426/167291850-69f6c1e7-9d54-44df-88d9-84be8dddae1b.png)

A shortened JSON response in productive mode (base name of exception only, no backtrace):

![Screenshot_20220508_120931](https://user-images.githubusercontent.com/7428426/167291867-85f5131b-22a5-46da-a851-2e4330e62b53.png)

That's how I wanted it. I was really concerned for some moment.

**Comment by qwerty287** [comment]
I'm sorry, I should take a look at the messages more carefully :)

**Comment by nagmat84** [comment]
It's all fine, I am just happy, that it is "only" a bug of the frontend and not another problem of the backend. :tada: :confetti_ball:
