### ISSUE TITLE
[Enhancement] Image Replacement / Versioning

### ISSUE THREAD

**Issue by axelrindle** [LycheeOrg/Lychee#1312]
I use Lychee to embed images (logo, brand header, etc.) in emails. When these images change, I must upload them as a new image whereby a new URL is created. I'd like to tell Lychee to create a new version of an image or just replace it with a new one but leave the URL untouched.

A replace action in the context menu could look like this:
![Bildschirmfoto vom 2022-05-07 20-43-27](https://user-images.githubusercontent.com/7105632/167267706-05fb2d34-34c8-4eab-a639-4229fbac3ad0.png)

**Comment by d7415** [comment]
To me, this feels way out of scope for a photo gallery.

What you want to do is host a file (e.g. yoursite.com/logo.png) and replace it when required.

**Comment by axelrindle** [comment]
> To me, this feels way out of scope for a photo gallery.
> 
> What you want to do is host a file (e.g. yoursite.com/logo.png) and replace it when required.

I already thought about that, but it would require a new deployment every time I change an image. The possibility to do that in Lychee would involve less effort.

**Comment by nagmat84** [comment]
There has already been a similar issue https://github.com/LycheeOrg/Lychee/issues/1100 asking for the same thing. However, if I understand your correctly you don't want to keep the history, but simply replace the image.

> I already thought about that, but it would require a new deployment every time I change an image.

Deployment of what?

Although I can imagine possible use-cases for https://github.com/LycheeOrg/Lychee/issues/1100 myself, I honestly don't believe that your approach is correct.

You said, you embed URLs to the images in emails. If i was the recipient of such an email,  I would want the email to look the same in 10 years as it does today. I would not want someone to magically exchange the image. Simply think of the case that your company logo is in landscape orientation and then - due to a rebranding - it is replaced by something in portrait orientation. If both were put under the same URL, that would destroy the layout of all previous emails which are already out in the world. These are two totally different images and they should deserve different URLs.

**Comment by axelrindle** [comment]
Thank you for the explanation. I will close this issue in favor of the one you mentioned.
