### ISSUE TITLE
[Enhancement] log SQL into database

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1340]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
Lychee doesn't send the SQL logs to the web interface. They are logged into the log file since they are logged directly by Laravel and not by our self-written `Logs::notice` feature. I don't know if Laravel supports a custom logger that could write the SQL logs to the database.

Might be interesting: https://laravel.com/docs/8.x/logging

**Comment by nagmat84** [comment]
It does. Some time ago I added a function which optionally logs all SQL queries to a file, if the option is activated in `.env`. So, yes this is possible, but I would not recommend that for a productive system as this essentially doubles the number of DB requests.

**Comment by qwerty287** [comment]
I know. But then it doesn't work on my local dev system. I have the log SQL option enabled, but they are only saved to the file, but not to the database. Or do I have to set another option?

**Comment by nagmat84** [comment]
That is what I wanted to say. I implemented a function which optionally logs all SQL into a file. Currently, there is no option or function to log SQL statements into the DB. All I wanted to say was that in principle it is possible to write a function which logs into the DB using the same approach as I did for logging SQL into a file. So you did not miss anything.

**Comment by d7415** [comment]
Just make sure you don't log the logging code!

**Comment by nagmat84** [comment]
That is one of the reasons why I decided to log into a file. But there are some more:

For productive systems it rarely makes sense to log the SQL statements. It would really increase the verbosity of the log and the length of the log message is limited to 100 characters which is by far too low to log enough of any SQL statement such that the log entry will be helpful. (Of course the latter can be fixed by a higher limit.)

IMHO, logging of SQL only makes sense for development systems. But here we have access to log files. Moreover, a log file has the advantage that it will also log errors if something is so extremely mis-configured that no SQL connection can be established (easiest case: the DB password is wrong).

Also note that SQL queries which fail at runtime and cause a PHP exception (e.g. a violated foreign key constraint) are logged to the `logs` table via the exception handler.

**Comment by qwerty287** [comment]
OK. I agree here, I'll just close it again.

**Comment by nagmat84** [comment]
That was not my intention. If you want to implement it go on. Why do people always think that I am against everything. 🤔 I just wanted to point out some aspects which need to be considered, but otherwise I am fine with such a function:

 - Increase the length of the log message (that's trivial except that I don't know what a good limit would be)
 - Ensure that SQL statements are only logged if explicitly enabled and that the log usually remains small. I know we have the function "clean noise" to remove everything from the logs which is below an error. But this does not prevent messages from getting into the log first. In this context, I would recommend introducing a new configuration setting like `log_severity_treshold` and the various logging functions only log a debug/informational/notice/warning/error message if the severity is higher than the treshold. This would also prevent performance issues due to logging every SQL statement unconditionally.
 - Ensure not logging the log statement and avoid infinite loops (obvious)

**Comment by qwerty287** [comment]
> That was not my intention. If you want to implement it go on.

No, there are too many disadvantages as you both pointed out.
