### ISSUE TITLE
No suitable image handler found

### ISSUE THREAD

**Issue by LouLeGrain** [LycheeOrg/Lychee#1432]
### Detailed description of the problem 
When trying to upload a photo, after uploading and processing, it fails with the message _No suitable image handler found_

### Output of the diagnostics 
Result of `php artisan lychee:diagnostics`
```
Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

System Information
------------------
Lychee Version (git):            master (1064f04) -- 5 commits behind master f39be7a (33 minutes ago)
DB Version:                      4.5.2

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     8.1.8
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        Europe/Berlin
Max uploaded file size:          64M
Max post size:                   64M
Max execution time:              50000
SQLite Version:                  3.27.2

exec() Available:                yes
Imagick Available:               -
Imagick Enabled:                 0
Imagick Version:                 -
GD Version:                      2.2.5

Config Information
------------------
version:                         040502
check_for_updates:               1
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         0
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            fr
layout:                          1
image_overlay_type:              date
default_license:                 reserved
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             1
landing_owner:                   L**** L******
landing_title:                   DoubleLShots
landing_subtitle:                Shooting film, not bullets, obvioulsy
landing_facebook:                https://www.facebook.com/doubleLshots
landing_flickr:                  https://www.flickr.com/photos/louislegrain
landing_twitter:                 
landing_instagram:               https://www.instagram.com/doublelshots
landing_youtube:                 
landing_background:              dist/bg.jpg
site_title:                      DoubleLShots
site_copyright_enable:           1
site_copyright_begin:            2022
site_copyright_end:              2022
additional_footer_text:          
display_social_in_gallery:       1
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      0
public_starred:                  0
downloadable:                    1
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           1
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       1
nsfw_warning:                    1
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1
Content-type: text/html; charset=UTF-8
```
### Error logs :
```
2022-08-02 18:22:20 UTC -- error   -- ::exif_read_data -- 180 -- exif_read_data(lychee-H4_IIjB_N3xTr4nC.jpg): Process tag(x0000=UndefinedTag): Illegal format code 0x0000, suppose BYTE
2022-08-02 18:22:20 UTC -- error   -- App\Image\GdHandler::load -- 191 -- Failed to load image; caused by
2022-08-02 18:22:20 UTC -- error   -- App\Image\ImageHandler::load -- 75 -- No suitable image handler found; caused by
2022-08-02 18:22:20 UTC -- error   -- ::exif_read_data -- 180 -- exif_read_data(lychee-H4_IIjB_N3xTr4nC.jpg): Process tag(x0000=UndefinedTag): Illegal format code 0x0000, suppose BYTE
2022-08-02 18:22:20 UTC -- error   -- App\Image\GdHandler::load -- 191 -- Failed to load image; caused by

```
### Browser and system
Chrome 103.0.5060.134 (official build) (x86_64) on MacOS Cataline 10.15.17

## Some info just in case : 
I'm hosting it on a Ionos (ex 1and1) hosting, it has imagick but renamed into `convert` (located at `/usr/bin/convert`), maybe i could use imagick if i can somehow tell the path to the piece of software who needs it.

**Also** i migrated my lychee, i wiped the folder, pull the last version from the repo, then `composer install --no-dev`, generated keys with artisan, the only thing i kept was the sqlite database and the public/uploads folder

Thanks alot for making Lychee !

**Comment by qwerty287** [comment]
Does it fail for any image or only for one specific? BTW your version is out-of-date, you should update :)

**Comment by nagmat84** [comment]
We see two problems here.

 1. Imagick is not found.
 2. GDImage bails out because it tumbles across some unexpected byte sequence in your image

Problem 1 alone would not trigger the bug, because Lychee falls back to GDImage as an alternative. But GDImage is unable to do the job.

No there is no way to specify an alternative path to Imagick, because Imagick is not called as an external command but as a PHP extension which in turn loads Imagick as a library. Please ensure that the PHP Imagick extension is installed and enabled.

**Comment by kamil4** [comment]
Yeah, we definitely would like to have access to the image that triggers this.

An alternative to using Imagick in this case would be to install Exiftool and set `has_exiftool` to `1` -- there's a chance that that workaround would work in this case.

**Comment by LouLeGrain** [comment]
> Does it fail for any image or only for one specific? BTW your version is out-of-date, you should update :)

I tried with several images, and it occurs only with the ones of my last batch, so they're very likely to be the cause.
I process all of them with [darktable](https://www.darktable.org/) v3.3.2, i'm late on the updates on this one too so i'm gonna get the last one right now.

Anyway here's a [small archive](https://drive.google.com/file/d/1EO7TJDogvGHSpUvn4KzYlY4EUBylUuSE/view?usp=sharing), with three of them, i'll delete it once you got them.

But you have a point there with my out of date version : i checked into the sqlite db and the version number (040502) was not updated (because i kept the db, reinstalled a fresh version of Lychee, and put it back along with the `/public/upload`
folder)
Maybe i missed a migration in the process ? As you can see my Lychee version is quite recent.
```
Lychee Version (git):            master (1064f04) -- 5 commits behind master f39be7a (5 hours ago)
    DB Version:                      4.5.2
```
Or maybe the DB version and the Lychee one aren't related ?

---

> Please ensure that the PHP Imagick extension is installed and enabled.

With a quick `php -m | grep imagick` on my host, it doesn't have the php module installed, unfortunately i have a very limited control on the server so i'll have to deal with it. 
I tried to put a `php.ini` file with `extension=imagick.so` at the root of Lychee, with no effect.
Same thing with exiftool, i can't sudo, nor use pecl, looks like a dead end with this low cost webhost...

---

Edit: after updating darktable to the last current version (4.0.0), re-exporting an image, and re-uploading, the bug still occurs

**Comment by kamil4** [comment]
I think @qwerty287 was just kidding about you being out of date: your tree is only a week behind. You are fine.

Anyway, back to the issue at hand. I have a question to other developers, especially @nagmat84 I guess. When I invoke `exif_read_data` on one of the supplied images from an interactive CLI PHP session, I get:
```
PHP Warning:  exif_read_data(IMG_1945_08-2022.jpg): Process tag(x0000=UndefinedTag): Illegal format code 0x0000, suppose BYTE in php shell code on line 1
```
However, the function succeeds, returning an array filled with plenty of EXIF tags. So I guess this is one of those idiotic PHP error "handling" cases where people would often use the `@` prefix to silence the pointless warning? In Lychee, however, instead of a warning we get an exception instead. So not only does the `exif_read_data` not return the EXIF info but also, the whole GdHandler's `load` method fails even though the image was successfully loaded and it's just the final auto-rotation attempt that can't be completed due to the failure to load metadata. So I guess I have a question and a suggestion:

Question: is it possible to prevent `exif_read_data` from throwing an exception in case of PHP warnings? (PHP errors would be another matter, of course)

Suggestion: irrespective of the answer to the above, I think we should modify GdHandler's `load` so that failure in `exif_read_data` is not treated as fatal.

**Comment by nagmat84** [comment]
> So I guess this is one of those idiotic PHP error "handling" cases where people would often use the @ prefix to silence the pointless warning?

I assume so.

> Suggestion: irrespective of the answer to the above, I think we should modify GdHandler's load so that failure in exif_read_data is not treated as fatal.

I am in favor. :+1:

> Question: is it possible to prevent exif_read_data from throwing an exception in case of PHP warnings? (PHP errors would be another matter, of course)

For the time being yes. This is what I would do:

We should wrap `exif_read_data` into our own helper method and then call this custom wrapper everywhere. I first thought this method might be a victim of using the `\Safe`-variants everywhere, but I found out again, that this isn't the case (see https://github.com/thecodingmachine/safe/issues/215). At the moment this comes to our advantage.

In our custom wrapper I would proceed as follows. Although I strongly discourage the use of the silence operator `@` in general, I would use it inside the wrapper before `exif_read_data`. Of course, we should  add a proper comment _why_ we use it there and also refer to this issue here as well as to the Errors/Exception section in [PHP Manual: `exif_read_data`](https://www.php.net/manual/en/function.exif-read-data.php).

Inside the wrapper we need to check for `false` manually and then explicitly throw an exception or return the array. If there has been a PHP engine warning, I would still create a proper exception via `last_error`, but _only_ forward it to the exception reporting and _not_ throw it for real.

This will buy us some time until more and more PHP engine warnings are converted to real exception. But hopefully there will be another solution to this problem by then.

Moreover I would like to add the faulty image to our automatic test suite. @LouLeGrain Do we have your permission for that? This would help us to ensure that this kind of image will continue to work in the future and it is really difficult to find good "negative" sample images which are faulty in a specific way.

**Comment by d7415** [comment]
> Or maybe the DB version and the Lychee one aren't related ?

040502 is the correct value for 4.5.2, so that's fine.

**Comment by LouLeGrain** [comment]
> I think @qwerty287 was just kidding about you being out of date: your tree is only a week behind. You are fine.

Aha didn't saw that, my bad. :)

@nagmat84 : I'm totally fine to add one of these images in your test suite, but only the landscape one, not the two others with my friends on it. I have other shots without people on it if you need several of them, but i'm assuming one would be enough ?

**Comment by kamil4** [comment]
> We should wrap `exif_read_data` into our own helper method and then call this custom wrapper everywhere.

Simple and "obviously right" idea that turns out to be a pain to implement. `exif_read_data` is called in only two places: once in the GdImage handler, and once in PHPExif. The latter, being nominally independent of Lychee, needs its own fix, which I just submitted there.

With just a single caller in the Lychee code base, can we avoid a wrapper and simply fix that one call, adding the necessary comments there of course? It will make things a whole less complicated that way...

> I first thought this method might be a victim of using the `\Safe`-variants everywhere, but I found out again, that this isn't the case (see [thecodingmachine/safe#215](https://github.com/thecodingmachine/safe/issues/215)).

Yes, I saw that -- there was a comment in our source code...

> If there has been a PHP engine warning, I would still create a proper exception via `last_error`, but _only_ forward it to the exception reporting and _not_ throw it for real.

Sorry, I don't understand. Can you point me at an example of what you mean?

**Comment by nagmat84** [comment]
> > We should wrap `exif_read_data` into our own helper method and then call this custom wrapper everywhere.
> 
> Simple and "obviously right" idea that turns out to be a pain to implement. `exif_read_data` is called in only two places: once in the GdImage handler, and once in PHPExif. [...]
> 
> With just a single caller in the Lychee code base, can we avoid a wrapper and simply fix that one call, adding the necessary comments there of course? It will make things a whole less complicated that way...

Sure, when I wrote up that idea, I didn't check that.

> 
> > If there has been a PHP engine warning, I would still create a proper exception via `last_error`, but _only_ forward it to the exception reporting and _not_ throw it for real.
> 
> Sorry, I don't understand. Can you point me at an example of what you mean?

I was referring to the same approach as used by the `Safe` package. Please don't take the following for 100% accurate, I am typing from a smartphone and switching between windows to look up method names or even typing special symbols is a PITA.

If a method generates a PHP engine warning or error it typically  sets the global PHP error variables. Sometimes they also do that when they only raise a warning even, but still return a useful result. I don't know what approach `exif_read_data` is using. Moreover, the PHP global error messages contain a telling error message which we can use to create a nice exception. Basically something like this

```php
error_clear_last();
$exifDataOrFalse = @exif_read_data(...);
$error = error_get_last();
if ($exifDataOrFalse === false || $error !== null) {
  $errorMsg = $error['message'] ?? 'exif_read_data() failed with unknown reason';
  $ex = new SomeLycheeExceptionWhichSeemToFit($errorMsg);
  if ($exifDataOrFalse === false) {
    // something went wrong catastrophically, throw the exception as `exif_read_data` would have done without @
    throw $ex;
  } else {
    // exif_read_data() returned an array and has been able to extract some useful data, but still reported a warning; don't throw the exception, but log it and proceed
    Handler::reportSafely ($ex);
  }
}
```
