### ISSUE TITLE
Version update issue

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#1446]
Hello.

I did not update Lychee for a while.. and just after "git pull", this is what I faced:

![putty_FNWTl5FBbW](https://user-images.githubusercontent.com/25976749/183260249-d1a386b0-4d83-42d2-a644-47ef370bd464.png)

If I am using "composer update", this is a result:
![putty_GxZRRBlnxm](https://user-images.githubusercontent.com/25976749/183260364-d4fad654-1282-4990-8f74-389e9aefc9af.png)
So.. "stand with Ukraine" and... it freezes... ; /

Can anybody write me, what to do now ?
I suppose there were some changes to hmm... composer or PHP version ?

It's on Debian 11. Everything worked fine until I tried to update the webapp with fresh files from github.

Hope somebody knows what is going on my screen.

**Comment by nagmat84** [comment]
I also encountered the "passing null" error once. For me it happened, because the PHP version was too new for my version of composer, or to state it the other way around, composer was too old. At some point, PHP started to enforce parameters to be non-null when their type annotations did not allow for nulls, and the previous composer version did not take care of it.

If you are hitting the same problem (I  not entirely sure), then you cannot use that composer version to do a self-update, because you will always run into that problem again and become stuck.

You need to download a modern version of composer from the composer homepage.

**Comment by ildyria** [comment]
I think @nagmat84 comment is the reason of this.
