### ISSUE TITLE
Shared albums which require a direct link for anonymous users are not visible to users with whom they are shared

### ISSUE THREAD

**Issue by flaki** [LycheeOrg/Lychee#1478]
### Detailed description of the problem

I realized during testing that not all shared albums I shared with a certain user would show up in the gallery once logging in with the other user. This was strange as it was only specific albums that would not show, always the same ones across users. I copied the URL to check if the album would be accessible that way, and sure it was: just would not show up in the gallery alongside the other albums.

At this point I realized the common thing between the albums were that they were all set to "Public". Somehow this seems to interfere with Albums::get, which does not list these albums in the API result.

### Steps to reproduce the issue

1. Create an album and share it with a user, confirm that it shows up in their gallery
2. Create another album, but set it to "Public" visibility (first three toggles on) before sharing it with an user
3. Confirm the album does not show up in that user's gallery, but is correctly accessible by its URL

### Browser and system

Lychee latest release built from Docker, running on LXC on Debian, up-to-date Firefox

**Comment by kamil4** [comment]
I can't reproduce it here locally. Could you attach the output of the diagnostics to this issue? Does it _always_ fail in the same way for you? Are we talking top-level albums here (not sub-albums)? Do you create the albums as admin or as another user?

**Comment by nagmat84** [comment]
Indeed very weird, especially as I thought that most cases, i.e. also mixed cases, are nowadays covered by tests, like this one

https://github.com/LycheeOrg/Lychee/blob/7ba064f20b8f4498e6d124fdf3d97f7d8ba2e92a/tests/Feature/SharingTestScenariosAbstract.php#L878-L889

Of course, this doesn't mean that there isn't a bug lurking somewhere and tests are never complete. But I really had hoped that I covered most if not all of the obvious "low-hanging fruits".

I am excited to see what is going on.

**Comment by flaki** [comment]
Okay I think I figured it out, according to the dumped SQL statements it seems that `requires_link` is tested to be `false` even for shared albums -- that is, public **hidden** albums (orange-colored eye icon) don't show up when shared with another user which may follow 'the word of the law' but not the intention, I'd expect that these *do* show up. I tested this by temporarily disabling "hidden" on a public, shared album (green eye icon) and it would then correctly show up on the other user's gallery.

(Context: I want to be able to share photo albums with family and close ones, while I'm *also* interested in sharing the same albums with certain people by setting them to 'hidden public' and sending them the link)

**Comment by flaki** [comment]
> the album does not require a direct link and is shared with the user, or

Hmm this [seems to be](https://github.com/LycheeOrg/Lychee/blob/7ba064f20b8f4498e6d124fdf3d97f7d8ba2e92a/app/Policies/AlbumQueryPolicy.php#L156) *intended* behavior which is weird to me because if I can't mark the public album hidden (accessible with the link only) then what's the point in sharing it - public non-hidden albums are accessible to everyone, including authenticated users :shrug:

**Comment by ildyria** [comment]
I would see this as an oversight of our side.
I do agree that an album shared to a user should not have the need for `require_direct_link`.

**Comment by nagmat84** [comment]
Well, I would not call it a bug but a feature as it works as specified. Surely, one might discuss if the specification is the way how it should be.

> At this point I realized the common thing between the albums were that they were all set to "Public". Somehow this seems to interfere with `Album::get`, which does not list these albums in the API result.

So it should have been

> At this point I realized the common thing between the albums were that they were all set to "Public" **and "Hidden"**

This explains it.

But back to the root problem. At the moment, we have what I would call an unfortunate mix with respect to the management of  permissions between user and albums. This is due to historic reasons, as multi-user support was added later. Hence, we have some album-wide settings (such as "hidden") which historically only affected anonymous users, because Lychee was a single-user system and there was only the owner and the rest of the world. Then multi-user support entered the stage, but the only thing what can be done until today is to select whether the album should be shared with another user or not. This leaves it somehow unclear which album-wide settings should also affect the share settings and how.

By the way: Just now we are working on a new approach to unify things and make the option to share albums with users more powerful and useful. See here for a heads-up: https://github.com/LycheeOrg/Lychee/issues/1462#issuecomment-1221603285

But back to the special case of `is_hidden`:

I also feel that it mostly makes sense for anonymous users only. This is also how the proposed change above uses it. However, there also seem to be users which use "hidden" in combination with users, although I lack the imagination why. For example, see here https://github.com/LycheeOrg/Lychee/pull/1357#issuecomment-1215763003 third bullet point. So maybe "hidden" just should become a per-share option.

**Comment by flaki** [comment]
Based on the (short) while I have been playing with Lychee and reading the issues here I do agree that there are some unfortunate decisions (many of which are rooted in legacy behavior) around sharing. I would agree that multi-user is the way forward, and especially with full shared albums (like many other tools offer, allowing uploads by multiple users, and I have read and agree that it's not trivial).

Similarly, the context [noted above](https://github.com/LycheeOrg/Lychee/issues/1478#issuecomment-1223638129) is a practical workaround for the fact that one-off "sharing links" cannot yet be generated for albums. I would wager that if that was possible "hidden public" albums would be probably largely obsoleted.
