### ISSUE TITLE
Delete user with album trigger API Error (v4.4)

### ISSUE THREAD

**Issue by sonblawher** [LycheeOrg/Lychee#1552]
### Detailed description of the problem [REQUIRED]
I deleted a new user with an empty album and I could not login to the admin account after that.

### Steps to reproduce the issue
1. Create a new user with a new album
2. Delete the new user
3. Try to login with admin account
4. See API error with an empty screen

### Output of the diagnostics  [REQUIRED]
I do not have the output

### Browser and system
Lychee V4.4 on Yunohost Debian 11

### Solutions
I modified the id_user of the orphan album with the id of the admin with phpmyadmin and it worked

**Comment by kamil4** [comment]
Lychee 4.4 is considered an old release at this point. A lot of development has taken care since then, with the current version being 4.6.1.

I tried the scenario you described with 4.6.1, and the album ownership gets changed to admin on user deletion, so it looks like the bug you describe has been fixed.

**Comment by sonblawher** [comment]
Great 😁
