### ISSUE TITLE
[Enhancement] Add real links to albums

### ISSUE THREAD

**Issue by Tragen** [LycheeOrg/Lychee#1704]
Go to https://lycheeorg.github.io/demo/ and hover with the mouse over the different albums.
There is no link so you cannot open the album with a middle click in a new tab.
The same problem is with any picture inside an album.

**Comment by ildyria** [comment]
Will have to wait for a revamp of the front-end.

**Comment by vasilevich** [comment]
I think, to support such a thing, first of all the project has to change the way it does links,

instead of using # with codes which might work but is clumsy and i think not even indexable properly,
eg  myphotosite.com/#1234567
should just be something like myphotosite.com/1234567 or myphotosite.com/album/1234567
it should work with the browser history api.
a website that works like that for example is github.com , when you click things, it just performs history.push with the new url
and then things can have custom links more easily
maybe the blade templating engine has some good routing support for this way too, in conjunction with the browser history api

**Comment by ildyria** [comment]
Yes... That is why I am exploring the Livewire option. Unfortunately, I don't have a lot of time IRL to work on Lychee with my current work + other hobbies...
