### ISSUE TITLE
WebAuthn.js does not work on older Safari versions

### ISSUE THREAD

**Issue by nicokaiser** [LycheeOrg/Lychee#1710]
Since (about) version 4.7, Lychee does not work in older Safari browsers. Safari <= 13 is present on older iOS versions, and most probably some older android devices are also affected.

The culprit seems to be the new WebAuthn.js, which uses private class methods, and which is directly committed into the dist folder (and thus not being transpiled by the Babel task in Lychee-front.

Has this been a deliberate choice, or should the files in dist also be somewhere else and included in the transpilation step?

I‘d happy to help with a PR, but am not yet familiar with the interweaved structure of Lychee and Lychee-front…

**Comment by doclbn** [comment]
I can confirm this behaviour on iPadOS 15.7.2 (release date 2022-12-13).
iOS 16.x seems to be unaffected.
I noticed this after migrating from 4.6.0. to 4.7.0

**Comment by d7415** [comment]
Looks like Safari 13 was EOL'd in 2020, so there are probably bigger issues than Lychee. Android is unlikely to have the same issue, at least to the same extent.

The effect @doclbn is reporting on an apparently recent version is more concerning, but at a glance shouldn't be related to private class methods.

**Comment by nicokaiser** [comment]
Although it might be relatively easy to achieve compatibility with Safari 13 (and probably other EOL'd browser versions) by using the (already existing) transpilation for all JS, I see that supporting dead browsers is not the top priority.

I could successfully compile a Lychee version that transpiled WebAuthn.js and ran in Safari 12, however this version hat problems opening the photos page then, and so I postponed my efforts on this.

**Comment by nicokaiser** [comment]
> I can confirm this behaviour on iPadOS 15.7.2 (release date 2022-12-13).

Could you try if https://gallery.kaiser.photo works better than vanilla 4.7.0? This currently runs on a custom version with transpiled WebAuthn and ResizeObserver polyfill. On iOS 12 it loads, but the photo view does not scroll to top (where the big photo is being loaded). This might be something minor and is still better than a blank page…

**Comment by nicokaiser** [comment]
I guess the remaining thing is the „overflow: clip“ CSS property, which is only supported for some months in Safari (>=16). It cannot be replaced with „hidden“ in this case, because that would render the page unscrollable. Any ideas?

**Comment by d7415** [comment]
I see that Apple were over a year behind everyone else implementing that one :man_facepalming:

**Comment by doclbn** [comment]
> > I can confirm this behaviour on iPadOS 15.7.2 (release date 2022-12-13).
> 
> Could you try if https://gallery.kaiser.photo works better than vanilla 4.7.0?

Sorry for late reply; it snowed so nicely today I had to go out skiing :)

Short answers first: trying vanilla 4.7 <-> Nico‘s patched version:
- iOS 12.5.6: no rendering (blank screen) <-> working photo display, but a little awkward rendering; see iOS 15
- iOS and iPadOS 15.7.2: some awkward rendering, will detail below <-> no difference as far as I can see; I‘d have to be able to log in to check further.
- iOS 16.2: Site works more or less as expected <-> no difference.

Very nice photos, btw; I particularly liked the cathedral ceiling :)

„Awkward“ stuff on iOS15 (and on iOS12 using Nico‘s fix):
- you can always swipe left and reveal the „info“ screen, even on pages that don‘t normally feature one
- if you open the info screen, it pushes away / displaces the album thumbs instead of overlaying them (which would be the intended behaviour on a small screen, I assume)
- upon touching an image thumbnail in an album, the larger version is displayed  at the top of the thumbnail list but I have to scroll up to the top to view it. I can - or rather I have to - swipe-scroll down again to continue viewing. No easy way to return to your former position in the album thumbnail list.

Not sure if this belongs here but I noticed these problems on iOS 16, too:
- the now overlaying info screen has a quite high transparency which makes it hard to read if it overlays brighter images (on Chrome / Edge the info screen does not overlay but displaces the thumbnails)
- I can‘t access the „open original“ link on images although it is allowed in the album permissions - the „…“ icon is not shown (or did I miss something here that has changed?)

Thanks for seeing into this!
-Lars aka doclbn

**Comment by doclbn** [comment]
… oh and I forgot: another iOS thing happens (on 15 [edit: NOT on 16], can‘t check on 12 for blank screen):
After logging in, the settings („gear“)  screen overlays the top page with 100% transparency, making it quite hard to navigate:

![8AE83B43-5B96-4E80-912C-D03B2C780FA3](https://user-images.githubusercontent.com/108540567/213879335-2d67b76f-6f1c-4548-8d32-f2f12eb0343c.jpeg)

-Lars

**Comment by nicokaiser** [comment]
I think most of the awkward rendering issues stems from Safari 15 not supporting „overflow: clip“. You can change the few „clip“ values to „hidden“ (either editing the CSS or using the Inspector and remote control Safari Mobile from a Mac) and the issues are gone – however the list view cannot be scrolled anymore then.I‘m not too much into CSS in general, and into the Lychee-front CSS in particular, but maybe someone can come up with an easy solution to fix both issues, Safari < 13 rendering a blank page and Safari < 16 (which is not EOL‘d and only some months old) rendering some things in awkward ways…Am 21.01.2023 um 18:07 schrieb Lars Brinkmann ***@***.***>:﻿

I guess the remaining thing is the „overflow: clip“ CSS property, which is only supported for some months in Safari (>=16). It cannot be replaced with „hidden“ in this case, because that would render the page unscrollable. Any ideas?



I can confirm this behaviour on iPadOS 15.7.2 (release date 2022-12-13).

Could you try if https://gallery.kaiser.photo works better than vanilla 4.7.0?

Sorry for late reply; it snowed so nicely today I had to go out skiing :)
Short answers first: trying vanilla 4.7 <-> Nico‘s patched version:


iOS 12.5.6: no rendering (blank screen) <-> working photo display, but a little awkward rendering; see iOS 15


iOS and iPadOS 15.7.2: some awkward rendering, will detail below <-> no difference as far as I can see; I‘d have to be able to log in to check further.


iOS 16.2: Site works more or less as expected <-> no difference.



very nice photos, btw!



„Awkward“ stuff on iOS15 (and on iOS12 using Nico‘s fix):

you can always swipe left and reveal the „info“ screen, even on pages that don‘t normally feature one
if you open the info screen, it pushes away the albums instead of overlaying them
upon touching an image thumbnail in an album, the larger version is displayed  at the beginning of the thumbnail list but I have to scroll up to the top to view it. I can - or rather have to - swipe-scroll down again to continue viewing. No easy way to return to your former position in the album thumbnail list.

Not sure if this belongs here but I noticed this On iOS 16:

the now overlaying info screen has a quite high transparency which makes it hard to read if it overlays brighter images
I can‘t access the „open original“ link on images although it is allowed in the album permissions - the „…“ icon is not shown (or did I miss something here that has changed?)

**Comment by qwerty287** [comment]
The linked PR has been merged in a new version
