### ISSUE TITLE
[Enhancement/Bug] Visibility of nested public albums on front page

### ISSUE THREAD

**Issue by Domoel** [LycheeOrg/Lychee#1947]
I dont know if this is by intention or just some sort of bug but if one is creating a nested album within an album and define it as public, it is not shown on the fronpage as long as the parent folder is also marked public. This is somewhat annoying since it limits the capability to share certain albums with the public without messing around with the album structure itself. 

In addition to that the nested album marked as public is not shown within the smart album public, even if the parent album was flagged public. Is this by intention?

**Comment by ildyria** [comment]
This is intended behaviour.

You can still share that album via URL.
E.g. when sharing some specific album to a friend (e.g. the nudes you took of her) without revealing it to everyone and without having to create an account for each person you share that album with.

⁣Get BlueMail for Android ​

**Comment by Domoel** [comment]
Thats a bummer and really counter intuitive. :-/ 

Besides that I have the strong feeling that the general settings regarding "visibility" are not consistent. The bavior differs between "Albums" and "Pictures". To give you more content here:

If I change the visibility of an album from private to public, I have the possibility to adjust my settings with regards to the sub menu options (e.g. "original", "pw", etc.). 

![image](https://github.com/LycheeOrg/Lychee/assets/14920200/dd1243b1-60ee-4c98-b882-7a060c22396e)

If I want to change the visibility options for a specific picture, the sub menu options are not accessible like shown here:

![image](https://github.com/LycheeOrg/Lychee/assets/14920200/23d4d3b2-d487-4fe1-a96e-9a2034c84a0b)

I dont know if there is an option within the settings menu to align the bavior here but it seems like this is not the case.

**Comment by ildyria** [comment]
You are the first one to complain about that over the last 4 years of Lychee. So to me, it seems that it's pretty intuitive to 99% of our users.

Also the implementation of making any public album visible depending whether they are in a parent or not make it even less counter intuitive. Here you know that the tree is correct. What is visible is with green eyes. Simple. Clear.

Otherwise, it makes quite a big difference between the public view and the admin view. Making the change of public to private etc more complex when you need to track down a sub album that is popping up in guest mode.

For the difference between album view and photo view, I think you are missing the point : "Zur info dargestellt"

There are no plan to implement more than this. I personally don't find public per picture a useful setting and would be in favour to completely remove it, but YMMV.

(Answering from the middle of the English Channel)

⁣Get BlueMail for Android ​
