### ISSUE TITLE
Updating user failed

### ISSUE THREAD

**Issue by msman0** [LycheeOrg/Lychee#1964]
### Detailed description of the problem [REQUIRED]
I have updated to 4.6.2. If I login with the admin user I get error messages

 -- error   -- PDOStatement::execute -- 570 -- SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users.users_username_unique'

-- error   -- App\Models\User::save -- 60 -- SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users.users_username_unique'; caused by

-- error   -- Illuminate\Database\Connection::runQueryCallback -- 760 -- SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users.users_username_unique' (SQL: update ``users`` set ``username`` = admin, `users`.`updated_at` = 2023-08-03 21:53:16.780862 where `id` = 0); caused by

-- error   -- App\Models\User::save -- 60 -- SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'users.users_username_unique' (SQL: update `users` set `username` = admin, `users`.`updated_at` = 2023-08-03 21:53:16.780862 where `id` = 0); caused by

-- error   -- App\Exceptions\ModelDBException::create -- 50 -- Updating user failed; caused by

I can login after a refresh.

Login with an other non admin User works fine.

### Steps to reproduce the issue
every login with the admin user

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

How can I fix the login error messages? 
Thank you!

**Comment by ildyria** [comment]
Seems like you have 2 users with the name "admin".
One way to fix that is go to the Users page, and remove that duplicate user with username "admin".

**Comment by msman0** [comment]
Hi ildyria, thank you. I have looked at the user page, but no double entry of admin is there. Only the admin user and an other user are displayed. Is there an other way to display and delete the double entry?
Thank you.

**Comment by ildyria** [comment]
Do you have access to your DB and do this ?
```sql
SELECT id, username FROM users;
```

**Comment by msman0** [comment]
Yes I have access to the DB. With these query I get 3 users:
ID 0 has an unknown name with $2x$.... (a lot of characters)
ID 2 is my admin user
ID 3 is my viewer user

**Comment by ildyria** [comment]
okay, so that explains a lot.
ID 2 is not your admin user. The admin user is the one with ID 0 in your version. The unknown name is actually the bcrypt hash for the admin username (remnant from version 3). We migrated out of this now which is why your update is broken.

You can fix this in two ways.
1. change the username of user with ID 2 to something else, execute the migration
2. Or, update all the tables with `owner_id` (probably `photos` and `base_albums`, check if there are others) where `owner_id = 2` to `owner_id = 0`, in other words, transfer the ownership of the pictures an albums from user 2 to admin, and then delete user 2.

I would suggest version 1 because it is the easiest to fix if something goes wrong.
The query should be something in the like
```sql
UPDATE users SET username = 'somethingelse' WHERE id = '2';
```

**Comment by msman0** [comment]
Thank you very much solution 1 worked!
