### ISSUE TITLE
After updating to version 4.13, I am unable to create albums

### ISSUE THREAD

**Issue by prashbharadwaj1** [LycheeOrg/Lychee#2040]
I updated the version to 4.13. I am unable to create albums.
 MariaDB version: 10.6.14
PHP version: 8.1.21
Below is a snippet of error from the logs

PDOStatement::execute:580 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'legacy_id' at row 1
App\Models\BaseAlbumImpl::performInsert:105 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'legacy_id' at row 1; caused by
Illuminate\Database\Connection::runQueryCallback:801 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'legacy_id' at row 1 (Connection: mysql, SQL: insert into `base_albums` (`id`, `legacy_id`, `created_at`, `updated_at`, `title`, `description`, `owner_id`, `sorting_col`, `sorting_order`, `is_nsfw`) values (k6vGfiv2afe_S7kgXLpZzXiE, 16976783768420, 2023-10-19 01:19:36.841797, 2023-10-19 01:19:36.841797, streetphotos, ?, 1, ?, ?, 0)); caused by
App\Models\BaseAlbumImpl::performInsert:105 SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'legacy_id' at row 1 (Connection: mysql, SQL: insert into `base_albums` (`id`, `legacy_id`, `created_at`, `updated_at`, `title`, `description`, `owner_id`, `sorting_col`, `sorting_order`, `is_nsfw`) values (k6vGfiv2afe_S7kgXLpZzXiE, 16976783768420, 2023-10-19 01:19:36.841797, 2023-10-19 01:19:36.841797, streetphotos, ?, 1, ?, ?, 0)); caused by
App\Exceptions\ModelDBException::create:50 Updating base album impl failed; caused by
App\Exceptions\ModelDBException::create:50 Updating album failed; caused by

**Comment by MattGHarvey** [comment]
Same issue here and same message from the error log.

**Comment by morganmora** [comment]
I fixed this issue in my prod environment by changing the datatype in the DB to char and giving length of 24, same than 'id', do make a backup before performing the fix, since it can have unexpected side effects. U need to change for tables base_albums and photos: 
ALTER TABLE `base_albums` CHANGE `legacy_id` `legacy_id` CHAR(24) NOT NULL;
ALTER TABLE `photos` CHANGE `legacy_id` `legacy_id` CHAR(24) NOT NULL;

![image](https://github.com/LycheeOrg/Lychee/assets/5961277/ec493e35-c96f-4dfa-b60a-7d3c78c8ffad)

Hope this helps, meantime a proper fix have to be implemented.

**Comment by ildyria** [comment]
1.  This is not the proper fix you want to do.
2. "I updated the version to 4.13. I am unable to create albums." FROM WHICH VERSION?
3. The fix is actually in your configuration: enable `force_32bit_ids` and you will be good to go.

**Comment by ildyria** [comment]
Duplicate. #1852
