### ISSUE TITLE
[Enhancement] Subfolder Permission Inheritance

### ISSUE THREAD

**Issue by AresQQQQQ** [LycheeOrg/Lychee#2044]
I have installed Lychee, and it's the best open-source photo album I've ever used. 
However, I'm currently encountering an issue:
My album consists of multiple layers of folders. I've noticed that even when I set the parent folder to be publicly accessible, the subfolders do not inherit this setting. When accessed anonymously, I only see an empty folder.
I'm unsure if this is a result of my actions or if it's designed this way. 
I hope you can address this issue. Thank you!

**Comment by ildyria** [comment]
**This is intended by design.**

That way you can have top level folder public but hidden and sub folders are public. Allowing you to make a more granular visibility. I personally use it quite a lot to make sure that some contents are available to some and not others.

What you really want is this:
https://github.com/LycheeOrg/Lychee/issues/1411
