### ISSUE TITLE
Feature request: light theme for Lychee

### ISSUE THREAD

**Issue by neurosatan** [LycheeOrg/Lychee#2086]
hi, pls add light theme for Lychee.

Example
<img width="613" alt="000" src="https://user-images.githubusercontent.com/39633578/55897758-d6189480-5bc9-11e9-9981-78770bedae8b.png">

**Comment by Renset** [comment]
Finally, I'm working on a white [theme](https://github.com/Renset/lychee-flat-white-theme) for Lychee v4 for my own purposes. Probably I can try to create a pull request for this feature if it makes sense

**Comment by kamil4** [comment]
I for one would be in favor of having a light theme as an option. You may want to check LycheeOrg/Lychee-front#269 that was supposed to clean up our color management and thus make any subsequent color theming easier. I feel that it would be beneficial to get that PR cleaned up and merged first...

**Comment by nspirov** [comment]
I'd like to add to this issue that there are users for whom the dark theme is a SERIOUS problem. I have impaired vision and I am literally unable to use Lychee unless there is a different theme. The menus and all dialogs are just dancing in front of me.
I hope the developers will take this into account. I, for example, would be a paid user if I could, well, use it.

**Comment by qwerty287** [comment]
There's https://github.com/Renset/lychee-flat-white-theme which seems to be pretty up-to-date. However, I don't know if it works (it's not developed by us).

**Comment by nspirov** [comment]
> There's https://github.com/Renset/lychee-flat-white-theme which seems to be pretty up-to-date. However, I don't know if it works (it's not developed by us).

Ah thanks, I saw it above. I'll try it.

**Comment by lukewatts** [comment]
Since we're using Tailwind, it might make more sense to make the default theme light, and then we can use the darkMode correctly to easily offer both to all users with a simple dropdown, like the Tailwind site does...

<img width="489" alt="tailwind-dark-mode" src="https://github.com/LycheeOrg/Lychee/assets/4622166/5a7fb52f-e2bd-4f25-91e1-c38d365f3bbf">

Then we have the added benefit of being able to allow users to use whatever their OS/system is set to and easily add new themes via the tailwind config: [overriding the dark variant](https://tailwindcss.com/docs/dark-mode#overriding-the-dark-variant)

I've got some ideas on this, so I'll take a deeper look into it and see if it's something that can be done easily via the above methods.

**Comment by ildyria** [comment]
Hi @lukewatts 
I know that tailwind support the `dark:` attribute but I didn't feel like annotating the full html to support the duality of settings.

This work has been done too:
https://github.com/Renset/lychee-flat-white-theme

One thing I paid attention to was to not use tailwind predefined colors in order to make them more extendable for other users:
https://github.com/LycheeOrg/Lychee/blob/master/resources/css/app.css
