### ISSUE TITLE
Not able to access login page

### ISSUE THREAD

**Issue by jameswill** [LycheeOrg/Lychee#2120]
Hi,

I have tried installing latest package of Lychee i.e. 5.0.x and I am not able to see the login page.

On further debugging I found that the new livewire configuration is enabled by default and it is restricting the login page. When I set "LIVEWIRE_ENABLED=false" in .env file the login page loads properly.

Is there any chance where the setting is disabled by default ? So that everyone can access the login page. ?

**Comment by ildyria** [comment]
> Is there any chance where the setting is disabled by default ? So that everyone can access the login page. ?

To put it bluntly: I'm sorry but No. If you Lychee is properly set up, the login page is working fine.
If you are not able to access it, it is most likely due to your configuration being incorrect: e.g. working behind a reverse proxy and not having set-up `APP_URL`.

The old front-end (`LIVEWIRE_ENABLED=false`) is no longer going to be developed. It is currently provided as a fallback so that users can still be able to do their configuration while having something working, but no new functionalities will be added to it.

There is one edge case when serving Lychee from a directory with alias which is not supported, but it is on the things I plan to have a look later.

**Comment by jameswill** [comment]
HI,

I need further information.

Do we need to configure anything specific for livewire setting? Because I have filled APP_URL and Database details in installation form and it does not load the login page.

![image](https://github.com/LycheeOrg/Lychee/assets/6368036/808af3d7-2fea-4ce9-b8e8-ca757bbe102a)

I am using PHP 8.2 and Mysql 5.7

**Comment by ildyria** [comment]
Are you trying to access Lychee from a subfolder ?

**Comment by jameswill** [comment]
yes. Its a sub directory installation.

**Comment by ildyria** [comment]
To put it shortly, this is not supported (yet) by Lychee v5.

**Comment by jameswill** [comment]
I have tried in root directory as well and getting the same error.

I am on a shared hosting environment. Does v5 supports shared hosting environment ?

**Comment by ildyria** [comment]
> I have tried in root directory as well and getting the same error.

What do you mean? 

Lychee support shared hosting as long as your domain name points to the public folder. e.g. :

`https://lychee.example.com` => `/path-to-lychee/public`
