### ISSUE TITLE
Album by tags

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#48]
From: https://github.com/electerious/Lychee/issues/683

> When adding tags to pictures, if tags are common between multiple pictures, I would like to see the tag as an album.

**Comment by Aleshus** [comment]
Is there anybody who works on this? If not, I can try it myself. 

My idea is to place new item at "plus" menu at logged dashboard named "New tag Album". There will be edit box that will hold list of tags and below of it selected photos from normal albums. Tag albums will be listed in Smart albums.

One technical question I have about generating list of photos. If that list will be counted on request (as select on DB) or it will be precalculated in special table. Second variant is special case of hardcore cache and I am not fan of that. So I prefer first variant, with memory cache, but I dont know if project uses it for now.

**Comment by kamil4** [comment]
I don't believe that anybody is working on this at the moment, although there is an effort to improve tags support in https://github.com/LycheeOrg/Lychee/issues/654.

@ildyria recently reimplemented Smart albums support so he is certainly the most qualified to chime in on the technical aspect of things.

Having said that, we do _not_ precalculate counts and we certainly don't store them. One reason for that is that the results of such counts may differ depending on who asks. E.g., the administrator gets to see all the pictures, the owner all of their own, and a nog logged in user only the public ones.

**Comment by Aleshus** [comment]
I wrote, that Tag albums could be listed in smart albums area, but it was wrong way. Structure is not prepared for multilevel smartalbums  (obviously) and I want to reuse as much as possible. So better way will be to build tag album as normal album. For now I dont know if tag album will be able to contain its own photos or not.

**Comment by ildyria** [comment]
I'm sorry I took that long to get back at it. Was on vacations.

@Aleshus why do you think so ?

https://github.com/LycheeOrg/Lychee/blob/master/app/SmartAlbums/SmartAlbum.php
We could add a method to the base `SmartAlbums` class : `get_children()` which generate the children list.
This would allow you to customize what albums you want there by overloading the method.

There was some discussion about albums by date on the gitter also: https://gitter.im/LycheeOrg/Lobby?at=5f21cf1d27799668010d1bb2

**Comment by Aleshus** [comment]
Ok, support for hierarchy on SmartAlbum class could be added easily. But I thought situations, where you want to create tag album inside the normal album - so there is some work with presentation layer, because album detail cant draw smart albums.  Return list of `get_children()` will contain Album or some of its child with different presentation, so maybe it will need some rework too. I saw a lot of work on it for the first time, but maybe I was pesimistic :) 

For now I am able to draw tag album in SmartAlbums section on client, where data is retrieved from backend (mocked on service layer, I don't have DB layer done yet). So I will finish it as it is, without hiearchy support for now, because SmartAlbums is more sympathic way for me too.

**Comment by Aleshus** [comment]
I created pull request for this issue. Tag albums could be added from top level + menu and are presented as smart albums. When tag album is public, with no-logged state only photos from public albums are visible..
