### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [LycheeOrg/Lychee#605]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by ildyria** [comment]
Can you explain how this interact with Travis ?

**Comment by thomasrockhu** [comment]
@ildyria, I'm not too sure I understand your question.

**Comment by ildyria** [comment]
Typo "who" -> "How". I meant that travis CI is taking care of applying phpunit etc and at the end we had our scripts. I don't see how the GitHub team bot is helping in that one.

**Comment by thomasrockhu** [comment]
I apologize if that wasn't clear, using the app integration removes the need for the team bot. The bigger issue around this is to prevent future outages, even for teams that don't use a team bot already.

**Comment by ildyria** [comment]
okay. :)

**Comment by ildyria** [comment]
Hi @thomasrockhu I could not help to notice since we installed your app that it is "failing" our builds and I do not understand why. Could you share some lights on this with us?

We get something like that:
> :x: @codecov codecov/project — 56.78% (+-0.09%) compared to ...

I do understand that our coverage is not ideal (yet, slowly working on it). But it is frustrating to see this :x: while our CI is still passing (which is the most important for us).
In the project settings, we did set it as follows: https://github.com/LycheeOrg/Lychee/blob/master/codecov.yml

```json
    "coverage": {
        "precision": 2, 
        "range": [
            50.0, 
            100.0
        ], 
```
Which if I understand correctly means that the coverage needs to be at least 50%... We are at 56%, thus it should turn somewhat green. No ?

This is really annoying also in the PR tab e.g. here: https://github.com/LycheeOrg/Lychee/pull/570 As we cannot quickly differentiate when the CI is failing to passing (sorry but codecov is quite polluting here).

**Comment by thomasrockhu** [comment]
Hi @ildyria I'll take a look now!

**Comment by thomasrockhu** [comment]
Ok, so taking a look at your `yaml`, `range` is actually used to determine [Codecov UI colors](https://docs.codecov.io/docs/coverage-configuration#range). What you are actually looking for is `target`. I'm going to open a PR to make the fix, but it'll look like

```
    "coverage": {
        "precision": 2,  
        "round": "down", 
        "status": {
            "changes": false, 
            "patch": {
                "default": {}
            }, 
            "project": {
                "default": {
                    target: 50%
                }
            }
        }
    }, 
```
[Target](https://docs.codecov.io/docs/commit-status#target) sets the minimum coverage to block on.

**Comment by thomasrockhu** [comment]
Waiting for tests to pass, but https://github.com/LycheeOrg/Lychee/pull/607

**Comment by ildyria** [comment]
Thanks you so much for that quick fix! :+1:
I really like codecov for its simplicity of use and visual graphics. :smiley:

**Comment by thomasrockhu** [comment]
Absolutely! Feel free to tag me here if you run into any other issues.
