### ISSUE TITLE
Clear upgrade instructions [Enhancement]

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee#609]
Hi!
Can the wiki upgrade instruction be clearly described?
So far i learned that to upgrade the git version i need to do:

`
git pull &&
php composer.phar install --no-dev &&
php artisan migrate
`

And this seems to take care of the backend.

Then i realised that i probably need to do something similar to the frontend too...

`
cd public/Lychee-front &&
git pull &&
npm install &&
npm run compile
`

Is this sequence correct? does this upgrades eveything or i am still missing something?

**Comment by ildyria** [comment]
Hi, is the documentation page not complete enough? See [here][1] we also give detailed instructions for usage with git in one of the [section][2].

> And this seems to take care of the backend.

Actually it also takes care of the front-end (if you are not developing, which we assume to be 99% of our userbase) because the backend also provide the updated/compiled javascripts.

> Then i realised that i probably need to do something similar to the frontend too...
> 
> `cd public/Lychee-front && git pull && npm install && npm run compile`
> 
> Is this sequence correct? does this upgrades eveything or i am still missing something?

This sequence is correct only if you modified something in Lychee-front or you are working on it. 
Otherwise, it does not really matter as the back-end provide the compiled resources to the user. This is also why now in the process, it is simply a `git clone` instead of a `git clone --recurse-submodules` as we don't need to provide Lychee-front to the user. You will also notice that the [releases][3] do not provide Lychee-front directory for the same reason. It only contains sources files which are not relevant to 99% of our userbase.

If you are in the 1% left, then yes you need to use the sub module etc...
It may be worth including a paragraph about front-end back end in the contribution guide that being said.

If you want to improve our documentation, feel free to open issues [here][4] and PR [here][5]. :+1: 

Do tell me if this answer your questions, you can also ping us on [gitter][6].

[1]: https://lycheeorg.github.io/docs/update.html
[2]: https://lycheeorg.github.io/docs/update.html#update-using-git
[3]: https://github.com/LycheeOrg/Lychee/releases
[4]: https://github.com/LycheeOrg/LycheeOrg.github.io/issues
[5]: https://github.com/LycheeOrg/LycheeOrg.github.io/pulls
[6]: https://gitter.im/LycheeOrg/Lobby

**Comment by gardiol** [comment]
Thank you, much clearer now.
