### ISSUE TITLE
[Enhancement] UI/UX: give more information about the capabilities given to new users in the users page

### ISSUE THREAD

**Issue by Julianoe** [LycheeOrg/Lychee#748]
I know that it can feel explanatory for people working on and using Lychee4 daily.
But I personally I'm a tech savvy user, i develop websites for a living and I've been an active user of Lychee for years now BUT : even for me "restricted account" means nothing. It's not documented and there is just a "lock" icon on the "create user" page.

It's a bit distressing to have a screen that could potentially give access to other users to your Lychee and not know what parameter does what... Imagine for end users that are just using it and don't know what's up behind it.

I think that:
1) icons only are not sufficient by themselves, even with a title tag that may or may not allow the end user to have the name of the option. It's generally considered bad practice in UI to only provide an icon as information.
2) the name Restricted is not very self explanatory. 
3) we need to give end users some more "tips" or notice about what they allow their friends/contacts to do by creating them an account with or without the "restricted" or "allow uploads" icons ticked.

This issue is here to start a conversation about possible improvements on the user creation page.

**Comment by kamil4** [comment]
I'm the one responsible for the current hover string (see https://github.com/LycheeOrg/Lychee-front/pull/53). In my defense, there was no hover string there before so I still see it as an improvement :wink:.

So what this option does is it prevents the user from being able to change their own login/password. The idea is to have an account shared between multiple people, say, so that they all can upload to one album, or so that they can access some non-public content. Obviously, if any of those people could change the login/password, they would effectively lock the others out of that account; hence this feature.

This should definitely be described in the documentation at least but our current docs are incomplete...

I just noticed that this particular screen isn't even properly localized so clearly it was a quick hack job. So I'm sure we would all welcome suggestions on how to improve it, and, even more, pull requests :smiley:.

**Comment by Julianoe** [comment]
> I'm the one responsible for the current hover string

My remark was not at all a critic against the hover string. Simply I feel this is not sufficient for people to understand what is going on.

Also thanks for explaining to me what restricted "lock icon" user is. This is indeed not documented anywhere, and without you explaining to me I would have never known.
I feel there is real UI improvement to make this more explicit.

I can contribute some translation to french at least... once it's localized properly. I have no experience with Laravel unfortunately.

**Comment by ildyria** [comment]
For the translations, have a look here:

https://github.com/LycheeOrg/Lychee/tree/master/app/Locale

Where to change the front end to add translations and context in the user page:
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/view.js#L1437

How to access a local string from the JS side.
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/view.js#L1666

Please note that we have checks which ensure that each key in the English locale is present in every other languages (at least as place holder).

**Comment by Julianoe** [comment]
I contributed with some french locales update.
Thanks for pointing out how it works, i'm looking into it to understand :)

**Comment by ildyria** [comment]
Some interesting readings: 
- https://lycheeorg.github.io/docs/read-more.html
- https://lycheeorg.github.io/docs/node.html
