### ISSUE TITLE
404 on public/install

### ISSUE THREAD

**Issue by pa810p** [LycheeOrg/Lychee#760]
Hi, 
I've installed v4.0.7 from .zip
when accessing public folder I was redirected to public/install and got 404 not found status.

Could you please check why, public/install directory does not exist?

Thanks

**Comment by ildyria** [comment]
Because it does not need to exist. We use Laravel under the hood who is taking care of the routes. If some directories and files do not exist, it is intended. The install routes are defined in this file: https://github.com/LycheeOrg/Lychee/blob/master/routes/install.php

My guess is that your server (most likely nginx) does not have the rewrite module enabled.
I suggest you have a look at this part of the [FAQ](https://lycheeorg.github.io/docs/faq.html#i-have-an-error-404-and-im-using-apache-what-can-i-do)

**Comment by pa810p** [comment]
Hi, 
thanks for help, it was .htaccess in this case.

Thanks
