### ISSUE TITLE
Not possible to unselect "hidden" under sharing options

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [LycheeOrg/Lychee#880]
### Steps to reproduce the issue
Uploading new photo.
Under Sharing I can make the photo public, but I can not modify the other sharing options - e.g. Hidden is checkey by default. The dialog tells me that the information is shown just as information and the actual values can be "fine-tuned" by using global setting, however there are no global settings to be found.

**Screenshots**
![sharingopts](https://user-images.githubusercontent.com/10712111/105607544-98d1c680-5d9f-11eb-8601-b1752f0c9b91.png)

### Browser and system
Lychee v4.0.1
Chrome

**Comment by kamil4** [comment]
This is working as intended; it's just that you've stumbled on a rather obscure feature and probably _not_ what you were looking for. Allow me to explain:

The _recommended_ way of sharing your photos with the public in Lychee is to upload them into an album (created using `+` / `New Album`) and then to make that _album_ public using its sharing settings. You will notice that all the visibility options will then be available for you to fine-tune. All the photos inside the album will inherit the visibility settings of the album.

Now, Lychee does also have a somewhat obscure feature of making individual _photos_ public: either photos that are not in any album (those show under `Unsorted`) or that are in a currently private album. This is what you were trying to do. Such photos can be made public, but they will always be _hidden_, meaning that they will not be visible when browsing through the albums in public mode. One needs to know the URL of that individual photo in the gallery in order to see it.

The comment about _global settings_ refers to the settings available under `Settings` / `More`; see also https://lycheeorg.github.io/docs/settings.html. There are specific settings there, such as `full_photo`, `downloadable`, and `share_button_visible`, that determine the visibility settings of photos individually made public. There is no global setting for `hidden`; as already mentioned, that one is always true for such photos.

I hope this helps. I realize that our manual is currently lacking when it comes to user-facing features.

**Comment by Sesshoumaru-sama** [comment]
I don't understand the beviour then.
I uploaded a photo and made it public. Then I created a Tagged Album, which is public, but still the image is not public visible when I log out. What am I doing wrong?

Photo:
![img1](https://user-images.githubusercontent.com/10712111/105634042-6a65f100-5e5c-11eb-85c0-e62403b492f0.png)

Under the Public Folder the image is listed, but still with the Orange Eye:
![img2](https://user-images.githubusercontent.com/10712111/105634068-9d0fe980-5e5c-11eb-9b9d-904fc6de68af.png)

The images has the tag "Anime" and thus its part of the Tag Album for Anime.:
![img3](https://user-images.githubusercontent.com/10712111/105634095-c16bc600-5e5c-11eb-8284-23d1153af929.png)

Anime Tagged Album:
![img4](https://user-images.githubusercontent.com/10712111/105634325-bc5b4680-5e5d-11eb-9ec8-313f969e3c3e.png)

Public Appearance:
![img5](https://user-images.githubusercontent.com/10712111/105634415-2378fb00-5e5e-11eb-81f9-1e1f68199873.png)

When logged out I can see than the empty album "Anime".
This must be wrong. How to I get the image to show up?

**Comment by ildyria** [comment]
The smart albums only show pictures that are in **public and directly accessible album**.

Create another album, make it public, put a picture in it with the `anime` tag, it will show in your smart album _Anime_.

**Comment by ildyria** [comment]
if you set an image as public, it just means that this particular image is accessible directly via `view.php?...` or `view/...` (I don't remember which one because I don't use it).

**Comment by kamil4** [comment]
Yeah, it works the way it does because that photo is, again, _hidden_. There is no way to see hidden photos in public mode through browsing through albums. Not through public tag albums, not through public recent or starred albums, and not through public search (the latter features can be enabled in Settings). It works that way by design.

**Comment by Sesshoumaru-sama** [comment]
This is kinda inconsistent.
The tagged album "Anime" is set to be public and it selects an image based on a tag which itself it set public. Of cause the intuitve expectation is that this image is visible. You are basically saything that Public Tagged Albums only show images from other public made albums. Thats a major restriction which has to be clearly stated. Thats non-intuitive - which I consider bad.

It also prevents me from just having tagged albums in public. I would need an "All Images Album" to have that working. Thats really ... inconsistent. Thats not design. Thats just inconsistent.

**Comment by ildyria** [comment]
Yes and no.

This is for security reasons, to prevent leaking pictures that are in hidden/private albums. 

If you want to enable such behavior the behaviour you are thinking of, then you can just comment lines 44 to 56 in the following:
https://github.com/LycheeOrg/Lychee/blob/a368964afe5b7b9403ca97a1b7959f923e2f0b28/app/SmartAlbums/BareSmartAlbum.php#L42-L59

Or make a Pull request with an additional advanced setting `disable_safe_filter_smartalbums` (set to `0` by default) which you check if set to `1` in that function and if so return directly `$query`.

**Comment by kamil4** [comment]
> This is kinda inconsistent.
> The tagged album "Anime" is set to be public and it selects an image based on a tag which itself it set public. Of cause the intuitve expectation is that this image is visible. You are basically saything that Public Tagged Albums only show images from other public made albums. Thats a major restriction which has to be clearly stated. Thats non-intuitive - which I consider bad.

Tagged album is a recent new feature and you may well be right that the way it has been implemented ends up being counterintuitive. We -- the developers -- don't see it that way since we know how it's implemented and why. In other words, there are good historical reasons for the current behavior.

We remember when public mode had no possibility of smart albums, no search, and there were no tagged albums either. Back then, if a photo was made public individually, there was no possibility of accessing it other than by knowing its ID.

Then, at the request of our users, we added public search, public smart albums, and we accepted an external contribution of tagged albums. When those features were added, we realized their potential of accidentally exposing the until then hidden photos to the public. We decided that a conservative implementation -- where only the photos reachable through ordinary browsing of albums were included in the results -- would be the least surprising to our existing users.

Now, a new user such as yourself looks at the outcome and sees it as inconsistent, maybe even pointless. I get that. Maybe we made it overly conservative, preventing perfectly valid new use cases that haven't occurred to us.

So let's try to define what a new, more consistent behavior should be. I won't promise that we will change the default, but we may provide an option to enable it, as @ildyria suggested above.

First, what photos should we include? Off the top of my head, we currently filter out:
* public photos without a parent album (the ones that show in the `Public` smart album)
* photos individually made public (residing within a private album)
* photos in a public but password-protected album
* photos in a public but hidden album
* photos in an album that is in principle public, but whose ancestor is private, or hidden, or password-protected (i.e., imagine album `A` with subalbum `B`, with photo `P` in the subalbum; `B` is public, but `A` is not; as a result, `B` is effectively hidden)

Which of those cases do you think we should include in the results?

Second, results of which feature? Just tagged albums, or also smart albums (public `Recent`, public `Starred`), or maybe also search?

**Comment by Sesshoumaru-sama** [comment]
Of cause, no promissed made. Understood :)

I will make the following assumption: 
1) One image can at one point in time only be part of one "normal" album.*
2) A normal album can be made public or private.
3) A photo within a private album can still be marked public, hence be shared by direct link (photo ID is a random hash)
4) Hidden and Private is not the same (you can hide an album from being shown, but the content can still be public)

*if it can be part of multiple albums, which could be a feature, then private beats public

Under the aspect of consistency I would say the following - just as my opinion on intuitivity:
- All smart albums shall have the same behavior in regards to the images they pick
- All public images which are in no album are automatically part of the album "Public Smart Album" (PSA)
- The user can define the PSA as either public or private: Default = Private
- Private beats public, so public photo in private album or private photo in public album is private overall (also in hierachy)
- No other behavior of the image gallery or its selection strategy is changed

The rational behind is that the PSA is treated like a user created album, offering an easy to understand choise to the user. Make it private and all you upload and not put to an public album is hidden, make it public and its content can be selected by e.g. Tagged Albums.

For the cases you (@kamil4) described it means - selectable = Smart Album can pick it up:
public photos without a parent album (the ones that show in the Public smart album) -> **depends on its public state**
photos individually made public (residing within a private album) -> **Not selectable**
photos in a public but password-protected album -> **Not selectable**
photos in a public but hidden album -> **Selectable**
photos in an album that is in principle public, but whose ancestor is private, or password-protected -> **Not Selectable**
photos in an album that is in principle public, but whose ancestor is hidden -> **Selectable**

In case the user made anything in the path of an image private or password protected, including its parent albums up to the root, its understandable that its not supposed part of a publical selection, like a public smart album. The only point which hit me wrong was the case where its not part of any album, thus considered private by default. Security by design is a challenging topic. I guess if I could just go to the PSA and define if that album is public or private, it would become much more intuitive and still fosters privacy by design (because of the default being private) hence makes is easy and plausible.

The caviot:
Making an album pubic and select hidden would mean its not shown itself when logged out, but the images contained can be selected by a public tagged album, starrted album and whatever is going to come.

Sorry for the wall of text...

**Comment by ildyria** [comment]
> Making an album pubic and select hidden would mean its not shown itself when logged out, but the images contained can be selected by a public tagged album, starred album and whatever is going to come.

While I disagree with that but I don't mind accepting a PR which adds a slightly less _safe_ setting as described above.

**Comment by d7415** [comment]
> While I disagree with that but I don't mind accepting a PR which adds a slightly less _safe_ setting as described above.

I agree with both parts of this. The idea of a hidden public album is that only those with the URL can see it. If it's on the front page I see no reason for the album to be hidden in the first place.

**Comment by kamil4** [comment]
I just submitted a PR that implements part of what we discussed; check there (#932) for more details.

**Comment by Sesshoumaru-sama** [comment]
> I just submitted a PR that implements part of what we discussed; check there (#932) for more details.

Thanks. Sorry for the late reply. I was on a business trip with almost no internet access... in this day and age.

**Comment by ildyria** [comment]
I assume this is fixed with #932

**Comment by MondyNor** [comment]
This app sucks
