### ISSUE TITLE
Why I deleted selected albums and the photos still in the recent Album

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#890]
I tested it many times. This problem only happens in deleting Multi-selected albums.
Deleting albums one by one, photos in that album will be deleted. But when I deleted all albums together, lots of photos still in the recent Album. And I check "Photos" in the SQL, there also have the data of these photos.  And a lot of photos also still in public/uploads/big.

Browser DevTools Network     Album::delete Response is true.

Lychee logs show no error.

**Comment by ildyria** [comment]
That is weird.

**Comment by kamil4** [comment]
I looked into this and it's **bad**.

We look up all the albums passed as arguments to `Album::Delete` first, and then, for each of them one-by-one, we delete the photos inside, the (now empty) subalbums, and the (now really empty) album itself. The problem is that after we delete the first album, `_lft` and `_rgt` of remaining albums can change. So when we go on to delete the second album, we are going by the now obsolete `_lft` and `_rgt`. We can actually delete the contents of a wrong album! Create three sibling albums, multi-select the first two and delete them. The contents of the first and _third_ will get deleted.

A workaround I can think of is looking up the albums passed as arguments to `Album::Delete` one-by-one, to ensure that we always get an up-to-date version. But maybe there's a better fix? Also, this is the second bug in delete we are seeing. Can any other operations then delete be affected by this?

**Comment by ildyria** [comment]
I will fix it this weekend.
