### ISSUE TITLE
Trusted Proxies

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#944]
Ref LycheeOrg/Lychee-Docker#89

Lychee includes [`fideloper/proxy`](https://github.com/fideloper/TrustedProxy/) which appears to tell Laravel when to trust `X-Forwarded-*` headers. At a glance, it looks like it uses `app/Http/Middleware/TrustProxies.php` for its configuration.

Assuming I'm correct:
 - `10.0.2.2` is hardcoded as a trusted proxy. That's not ideal.
 - This can't be configured `.env`.

Thoughts?

**Comment by ildyria** [comment]
>  At a glance, it looks like it uses app/Http/Middleware/TrustProxies.php for its configuration.

The configuration should be forwarded to a Config/xxxx.php file and then loaded in TrustProxies.php via config("xxx.name").

The reason is there should be no `env()` function outside the Config folder. If a user decides to optimize his Lychee installation, the Config is cached and the `env()` functions return nothing.

**Comment by jrouly** [comment]
Hm. Is there a mechanism for hot loading custom php configuration files? Especially via Docker, which is why I initially filed this ticket there.

This sounds like something that might be nice to expose through an env config.
