### ISSUE TITLE
HTTP request to `/api/Album::get` with illegal or non-existing albumID returns a HTTP 200 instead of 404 or 422, resp.

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee#962]
I am working on an Android client for Lychee and use the [API documentation](https://lycheeorg.github.io/docs/api.html) as my starting point. (However, I still need to reverse-engineer a lot, because the JSON schema is undocumented).

I stumbled across a surprising aspect.

If I post a request to `/api/Album::get` with an empty string as album ID or a non-existing album ID, both times the Lychee responds with HTTP status 200 OK and a text message body which contains `false`.

In other words

    POST https://photos-dev.mhnnet.de/api/Album::get
    {"albumID":""}

returns

    200 OK https://photos-dev.mhnnet.de/api/Album::get
    Content-Type: application/json
    
    "false"

and

    POST https://photos-dev.mhnnet.de/api/Album::get
    {"albumID":"42"}

with "42" not being an existing album also returns

    200 OK https://photos-dev.mhnnet.de/api/Album::get
    Content-Type: application/json
    
    "false"

IMHO, the first one should be a 422 and the latter one a 404. Moreover, it would recommend to respond with a proper JSON object which explains the error. I am speaking about the following JSON response which one gets in other cases

    {"message":"The given data was invalid.","errors":{"albumID":["The album i d field is required."]}}

Returning 200 in the cases above makes it rather difficult to implement a client, because one must not rely on a correct HTTP status code which in turn makes it difficult to use 3rd party libraries like Retrofit2, OkHTTP and GSON out-of-the-box without patching around strange server responses.

**Comment by ildyria** [comment]
@nagmat84 are you working on this ? :) 

I may do a bunch of code refactoring soon on the back-end. So I would like to know in order to avoid making conflicts with you. :+1:

**Comment by nagmat84** [comment]
@ildyria Thank's for letting me know. Unfortunately, I haven't started to work on that yet. You know, the typical problems: too high-aimed goals, my actual work which pays my bills, family stuff, etc.

If you want start refactoring, do it. I will either wait until you have finished or make sure that I resolv the conflicts later.

**Comment by ildyria** [comment]
> my actual work which pays my bills, family stuff, etc.

Same for me (minus the family stuff, plus the sports stuff). :sweat_smile: 

I am currently working on a major refactoring of the front-end to move everything to Livewire. In the current state, there are things I am not happy with in the back end: conversion to array, back and forth...

Basically there are 3 things I want to do:

1. move away from the arrays implementations and use collections instead.
2. Json for everything the API spit out (instead of the mix-json/string) by an auto toArray convertion.
3. Not depend on Array for the new front-end. :)

Point 2, requires changes in the front-end... who knows how long this is going to take me. :(
