### ISSUE TITLE
GET requests to image files is neither protected by CSRF nor login

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee#965]
If one knows the URL of an image, for example `https://lychee.my-domain.tld/uploads/big/xxxxxx.jpg` with `xxxxxx` being the ID, it is possible to GET this image without being required to authenticate.
It seems as if only the API `/api/...` is protected by CSRF, a proper Laravel session cookie and a login.

**Comment by ildyria** [comment]
> If one knows the URL of an image, for example https://lychee.my-domain.tld/uploads/big/xxxxxx.jpg with xxxxxx being the ID, it is possible to GET this image without being required to authenticate.

That is indeed the case, and that is because Laravel is a PHP engine. Having to go through each request & CSRF for each single image would slowdown significantly the website. As a result images are directly served via Apache/Nginx. Feel free to propose a configuration that fix this.

Furthermore we provide a band-aid to this problem by allowing the admin to generate symbolic links instead of serving directly the images. The admin choses the TTL of the symLink, ensuring its death in a defined time span.

The problem of this approach is the large number of SQL requests significantly slowdowns the page upon first connection.

> It seems as if only the API /api/... is protected by CSRF, a proper Laravel session cookie and a login.

Yes, and I would argue that we do not need to protect the GET on images as they are not state changing:
https://security.stackexchange.com/questions/115794/should-i-use-csrf-protection-for-get-requests

**Comment by d7415** [comment]
Duplicate of #335
