### ISSUE TITLE
[Enhancement] Open image in new tab

### ISSUE THREAD

**Issue by endotronic** [LycheeOrg/Lychee#987]
This is not currently possible (in Chrome, anyway) since Lychee provides a custom right-click context menu.

One scenario this would help with is opening an album from search results without losing your place in the results. I find the "back" functionality does not work well in a big results set, and often I want to get to the album from search results.

I'm hoping this is quite small and a place you are already working in.

**Comment by kamil4** [comment]
The right-click context menu is only there for items you can edit. In particular, it's not there in public mode. But even then things don't work the way you would like because neither albums nor photos are hyperlinks (`<a>` HTML tags).

I have actually wondered for a while if we _could_ make them be regular hyperlinks and what the pros/cons would be. Even with the custom context menu, we could simply add an _Open in new tab_ item there.

Incidentally, I have been working on fixing the search results so that the back button works as it should for them -- see #931.

**Comment by endotronic** [comment]
Oh, that's awesome about #931. If the back button takes you back to the search results, does it keep your place in a long list, and is there a way to see the album if you wish to do that instead?

**Comment by kamil4** [comment]
> If the back button takes you back to the search results, does it keep your place in a long list,

Yes for photos. Not (currently) for albums in the search results -- thank you for asking the question -- I'll see if I can fix that before this gets merged.

> and is there a way to see the album if you wish to do that instead?

Yes, the back button works correctly for albums in the search results as well, also if after loading the album you click on any photos in that album. The back button will break, however, if you click on any _subalbums_ in that album.
